modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="rotm" #mandatory
version="1.0-1.19.4" #mandatory
displayName="Revolt of the Mobs" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/revolt-of-the-mobs" #optional
logoFile="rotmlogo.png" #optional
authors="Feroov" #optional
# (#mandatory)
description='''
Revolt of the Mobs transforms once-passive animals into fierce,
intelligent warriors armed with guns and ready to fight the player and other mobs.

Players must constantly be on guard as they navigate through this new and dangerous world,
utilizing their wits and skill to survive against the deadly foes.'''

[[dependencies.geckolib]]
    modId="geckolib"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
